### ISSUE TITLE
웹서버 만들기

### ISSUE THREAD

**Issue by JinwoongKim** [JinwoongKim/toy1#3]
- [x] 도커 파일 만들기
- [x] uvicorn 을 API 서버로 만들기
- [x] nginx와 연동

**Comment by JaewukLee** [comment]
Uvicorn image


```dockerfile
FROM python:3.9.2

RUN apt-get update -y
RUN apt-get install -y vim

RUN pip install uvicorn[standard]

RUN useradd -ms /bin/bash jwlee
WORKDIR /home/jwlee

COPY ./example.py .
RUN chown jwlee:jwlee example.py
RUN chmod +x example.py

USER jwlee

EXPOSE 8000
```

**Comment by JaewukLee** [comment]
![화면 캡처 2021-03-04 224918](https://user-images.githubusercontent.com/16644658/109973564-e563d680-7d3b-11eb-994a-dd73c275b45f.png)

**Comment by JinwoongKim** [comment]
나도 혼자 정리한다고 그림 그린거 있었는데, 올린다 구냥 ㅎ

<img width="1175" alt="Screen Shot 2021-03-07 at 20 59 24" src="https://user-images.githubusercontent.com/12505517/110239002-00c32180-7f88-11eb-9d58-9e47491da5c7.png">

<img width="1285" alt="Screen Shot 2021-03-07 at 20 59 33" src="https://user-images.githubusercontent.com/12505517/110239003-06206c00-7f88-11eb-9d4a-fcddc8f6c63f.png">

**Comment by JaewukLee** [comment]
nginx + uvicorn 구성을 구글링 했을 때 예제가 별로 안나옴
아무래도 내가 파이썬 환경의 웹서비스 구성 개념부터 공부한다음, 아키텍처를 다시 고민해야겠다는 생각이 듦.

내가 처음 들어본 것들의 기본 개념부터 다시 찾아봄

1. Flask, Uvicorn + FastAPI : Python 기반의 API 서버 개발
  - flask는 아직 공식문서 안봄. Uvicorn으로 API 서버 만들때는 FastAPI를 써서 RESTful 형태로 만드는듯함.
  - flask 단점은 API문서 자동화에 버그가 많다는 것. FastAPI는 API 문서화를 잘 지원함

----------------------------------
안나오긴 개뿔 떡하니 나옴

https://gitlab.com/Plaoo/library-microservices-example
https://sncap.tistory.com/993

**Comment by JinwoongKim** [comment]
<img width="897" alt="image" src="https://user-images.githubusercontent.com/12505517/111032262-a83fc880-844e-11eb-82e9-b51bdc6c5c8b.png">
